# Generated by Django 3.1.7 on 2021-02-24 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('deleted', models.BooleanField(default=False)),
                ('blocked', models.BooleanField(default=False)),
                ('moderator', models.BooleanField(default=False)),
                ('nick', models.CharField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=512)),
                ('last_login', models.DateTimeField()),
                ('tocken', models.CharField(default='', max_length=512)),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
