# Generated by Django 3.1.7 on 2021-02-24 07:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0002_auto_20210224_0814'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='tocken',
            new_name='token',
        ),
        migrations.AlterField(
            model_name='account',
            name='last_login',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 2, 24, 8, 25, 24, 5354)),
        ),
    ]
