# Generated by Django 3.1.7 on 2021-02-23 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='hearts',
            field=models.IntegerField(default=0),
        ),
    ]
